services:
  backend:
    build:
      context: ./backend
    container_name: parcel_proxy_backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:10000"
    volumes:
      - ./backend:/app
